42: &ardupilot
  uavcan.node.id:                 42
  uavcan.pub.note_response.id:    2341
  uavcan.pub.readiness.id:        2343
  uavcan.pub.setpoint.id:         2342

  uavcan.sub.dynamics.0.id:       2378
  uavcan.sub.dynamics.1.id:       2358
  uavcan.sub.dynamics.2.id:       2368
  uavcan.sub.dynamics.3.id:       2348

  uavcan.sub.esc_heartbeat.0.id:  2374
  uavcan.sub.esc_heartbeat.1.id:  2354
  uavcan.sub.esc_heartbeat.2.id:  2364
  uavcan.sub.esc_heartbeat.3.id:  2344

  uavcan.sub.feedback.0.id:       2375
  uavcan.sub.feedback.1.id:       2355
  uavcan.sub.feedback.2.id:       2365
  uavcan.sub.feedback.3.id:       2345

  uavcan.sub.power.0.id:          2376
  uavcan.sub.power.1.id:          2356
  uavcan.sub.power.2.id:          2366
  uavcan.sub.power.3.id:          2346

  uavcan.sub.status.0.id:         2377
  uavcan.sub.status.1.id:         2357
  uavcan.sub.status.2.id:         2367
  uavcan.sub.status.3.id:         2347

50: &prototype_esc # front right, CCW
  uavcan.sub.readiness.id:        2343
  uavcan.sub.setpoint.id:         2342
  # pwm2_ch:                        -1

  # pwm1_ch:                        0



  pwm1_ch:                        3
  pwm2_ch:                        0
  pwm3_ch:                        1
  pwm4_ch:                        2


# 51: # rear left, CCW
#   <<: *prototype_esc
#   pwm1_ch:                        1

# 52: # front left, CW
#   <<: *prototype_esc
#   pwm1_ch:                        2

# 53: # rear right, CW
#   <<: *prototype_esc
#   pwm1_ch:                        3

71:
  uavcan.pub.baro.press.id:       0
  uavcan.pub.baro.temp.id:        0
  uavcan.pub.gps.yaw.id:          2405
  uavcan.pub.gps.point.id:        2406
  uavcan.pub.gps.sats.id:         2407
  uavcan.pub.gps.status.id:       2408
  uavcan.pub.gps.pdop.id:         2409
  uavcan.pub.mag.id:              0
