id: 50
  name: mini
  pwm1_ch: 3
  pwm1_def: 1000
  pwm1_max: 2000
  pwm1_min: 1000
  pwm2_ch: 0
  pwm2_def: 1000
  pwm2_max: 2000
  pwm2_min: 1000
  pwm3_ch: 1
  pwm3_def: 1000
  pwm3_max: 2000
  pwm3_min: 1000
  pwm4_ch: 2
  pwm4_def: 1000
  pwm4_max: 2000
  pwm4_min: 1000
  ttl_ms: 500
  uavcan.pub.crct.5v.id: 3500
  uavcan.pub.crct.5v.type: uavcan.si.sample.voltage.Scalar.1.0
  uavcan.pub.crct.temp.id: 3501
  uavcan.pub.crct.temp.type: uavcan.si.sample.temperature.Scalar.1.0
  uavcan.pub.crct.vin.id: 3502
  uavcan.pub.crct.vin.type: uavcan.si.sample.voltage.Scalar.1.0
  uavcan.pub.feedback1.id: 2375
  uavcan.pub.feedback2.id: 2355
  uavcan.pub.feedback3.id: 2365
  uavcan.pub.feedback3.type: reg.udral.service.actuator.common.Feedback.0.1
  uavcan.pub.feedback4.id: 2345
  uavcan.pub.feedback4.type: reg.udral.service.actuator.common.Feedback.0.1
  uavcan.sub.readiness.id: 2343
  uavcan.sub.readiness.type: reg.udral.service.common.Readiness
  uavcan.sub.setpoint.id: 2342
  uavcan.sub.setpoint.type: reg.udral.service.actuator.common.sp.Vector4